# Site settings
title: CI and CD with GitHub
description: A demo blog
email: brainstarr@github.com
github_username:  brainstarr
baseurl:
url: https://githubtraining-cicd-demo.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

markdown: kramdown
